/* Generated By:JavaCC: Do not edit this line. DemoParserConstants.java */
package demo;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DemoParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SPR = 6;
  /** RegularExpression Id. */
  int SPRA = 7;
  /** RegularExpression Id. */
  int PRINT = 8;
  /** RegularExpression Id. */
  int MAIN = 9;
  /** RegularExpression Id. */
  int IF = 10;
  /** RegularExpression Id. */
  int BOOL = 11;
  /** RegularExpression Id. */
  int FUN = 12;
  /** RegularExpression Id. */
  int NEW = 13;
  /** RegularExpression Id. */
  int FOR = 14;
  /** RegularExpression Id. */
  int HEJ = 15;
  /** RegularExpression Id. */
  int ELSE = 16;
  /** RegularExpression Id. */
  int CIAG = 17;
  /** RegularExpression Id. */
  int RETURN = 18;
  /** RegularExpression Id. */
  int DOUBLE_PLUS = 19;
  /** RegularExpression Id. */
  int PLUS = 20;
  /** RegularExpression Id. */
  int MINUS = 21;
  /** RegularExpression Id. */
  int TIMES = 22;
  /** RegularExpression Id. */
  int AS = 23;
  /** RegularExpression Id. */
  int DOUBLE = 24;
  /** RegularExpression Id. */
  int DIVIDE = 25;
  /** RegularExpression Id. */
  int OPEN_PAR = 26;
  /** RegularExpression Id. */
  int CLOSE_PAR = 27;
  /** RegularExpression Id. */
  int OPEN_BRACE = 28;
  /** RegularExpression Id. */
  int CLOSE_BRACE = 29;
  /** RegularExpression Id. */
  int OPEN_SQUARE = 30;
  /** RegularExpression Id. */
  int CLOSE_SQUARE = 31;
  /** RegularExpression Id. */
  int NUMBER = 32;
  /** RegularExpression Id. */
  int VARIABLE = 33;
  /** RegularExpression Id. */
  int ASSIGNMENT = 34;
  /** RegularExpression Id. */
  int LESS_THAN = 35;
  /** RegularExpression Id. */
  int GREATER_THAN = 36;
  /** RegularExpression Id. */
  int LOGIC_EQUALITY = 37;
  /** RegularExpression Id. */
  int LOGIC_INEQUALITY = 38;
  /** RegularExpression Id. */
  int LOGIC_AND = 39;
  /** RegularExpression Id. */
  int LOGIC_OR = 40;
  /** RegularExpression Id. */
  int COMMA = 41;
  /** RegularExpression Id. */
  int SEMICOLON = 42;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "\"spr\"",
    "\"spra\"",
    "\"print\"",
    "\"main\"",
    "\"if\"",
    "\"bool\"",
    "\"fun\"",
    "\"new\"",
    "\"for\"",
    "\"hej\"",
    "\"else\"",
    "\"ciag\"",
    "\"return\"",
    "\"++\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"as\"",
    "\"double\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "<NUMBER>",
    "<VARIABLE>",
    "\"=\"",
    "\"<\"",
    "\">\"",
    "\"==\"",
    "\"!=\"",
    "\"&&\"",
    "\"||\"",
    "\",\"",
    "\";\"",
  };

}
